services:
  redis:
    image: redis:7
    container_name: sentinel-stream-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: sentinel-stream-postgres
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
      POSTGRES_DB: sentinel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: sentinel-stream-api
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
      POSTGRES_DB: sentinel_db
    depends_on:
      - redis
      - postgres

  worker:
    build: ./worker
    container_name: sentinel-stream-worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
      POSTGRES_DB: sentinel_db
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
